### PR TITLE
Facet styling

### PR DESCRIPTION
**Pull request by little9**
This adds styling to the facets that are
based on the c5 mockups.

Connected to UCLALibrary/ursus#282

### CODE REVIEW

**Comment by little9** [comment]
This is different from the C5 mockups in two ways:

The design calls for the selected term to look like a button/pill, but this won't look correct with
long subjects:
Screenshot from 2019-03-22 13-38-31

There is a beige/orange color in the date slider graph that is hard coded.

Here's what the facts look like with this commit: 
image

**Comment by little9** [comment]
@tinuola Here's the changes based on what we were doing yesterday:

Desktop:
image
Mobile:
image

**Comment by little9** [comment]
@tinuola They look like this: 
Annotation 2019-03-28 132821

The way that facets are implemented in that state in the C5 mockups is duplicating the functionality I circled in the above screenshot. I think that looks better than the C5 design, but if you really like the way it looks in the mockups, I'll see if I can change it! It will require rewriting a lot of the facet code in BL7 to get it to work that way though.

**Comment by tinuola** [comment]
@little9 How much more work (extra points?) do you estimate it might take to get closer to fidelity? We may want to discuss this at Standup today. I'm open to forgoing this aspect of the design spec if we can get search terms rendered this way : See attached. But this will be in another ticket I presume.

Screen Shot 2019-03-28 at 12 48 16 PM

**Pull request merged**
